# k8s/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsu-api
  template:
    metadata:
      labels:
        app: devsu-api
    spec:
      containers:
      - name: devsu-api-container
        image: salvadormenjivar/devsu-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: django_secret_key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: database_url