apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsu-api-ingress
spec:
  rules:
  - host: "devsu-api.local"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devsu-api-service
            port:
              number: 80