# k8s/secrets.yml

apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  #clave secreta de Django, única para este despliegue.
  django_secret_key: "D+x79wVrMmG2w6P+s4fHN8ObhA+d8kxWYfW3Ss7jbCc="
  
  # La URL de conexión a la base de datos.
  database_url: "postgres://devsuuser:devsupassword@postgres-service:5432/devsudb"